### ISSUE TITLE
Your former colleague would love to contribute

### ISSUE THREAD

**Issue by sarahkerriganMS** [Korriban/Ariadne#1]
Hi Christian, several timezones separate us, but I hope we can collaborate on this, if you don't mind my eagerness. I was looking for a Swift SpriteKit project I can contribute to but most projects target iOS rather than macOS environments. Besides, I already love the theme you have set up with your latest commits.

Looking forward to work with you in Germany soon. My Fraunhofer SIT position is getting renewed in April 🤗 
-Sarah

**Comment by ghost** [comment]
Hi Sarah, glad you like to contribute and you are welcome to do so. We already talked on skype recently but you seem to have changed your account. Add me sometime again.
Best wishes from the (your soon to be home) City of Science.

Sincerely, Christian

PS: branching and rebasing is much appreciated at this point in order to avoid conflicts with project specific structure changes. I recommend working directly on my repo instead of forking it outright at this stage, but I'll leave it up to you. 
One urgent warning upright: Wait for the TODO list so we can set up a project milestone list branching into item lists in confluence. You still have access to the intranet haven't you? So don't be TOO eager yet and keep me up to date.
